name: ebame8-aDNA-tutorial
channels:
  - conda-forge
  - bioconda
  - defaults
  - genomewalker
dependencies:
  - python=3.9
  - bowtie2
  - seqkit
  - samtools>=1.14
  - picard
  - bedtools
  - mapdamage2
  - htslib
  - csvtk
  - htslib
  - cxx-compiler
  - gsl
  - eigen
  - perl
  - r
  - r-tidyverse
  - r-ggrepel
  - bioconductor-rsamtools
  - r-viridis
  - pip
  - pip:
      - bam-filter
      - dmg-reads
      - get-read-percid
      - attrs
      - metaDMG[all]>=0.36.0
      - tabview
      - logger_tt
